# Application Configuration Template
# Copy this file to application.properties and fill in the values
# DO NOT commit application.properties with real credentials

# Redis Configuration
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.password=${REDIS_PASSWORD:}

# JWT Configuration
# Generate a secure secret with: openssl rand -base64 32
jwt.secret=${JWT_SECRET:change-this-to-a-secure-random-value-minimum-256-bits}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:sqlite:test.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
